@startuml parkinglot
skinparam Shadowing false
skinparam class {
    BackgroundColor PaleTurquoise 
    ArrowCollor SeaGreen
}

package parkingconfig <<Aggregate>> {
    class ParkingBoyConfig <<Entity>> <<Aggregate Root>> {
        -ParkingBoyConfigId id
        -String name
        -List<ParkingLotId> parkingLotIds
        -ParkingStrategyName parkingStrategyName
    }

    class ParkingManagerConfig <<Entity>> <<Aggregate Root>> {
        -ParkingManagerConfigId id
        -String name
        -List<ParkingBoyConfigId> parkingBoyConfigIds
    }

    class ParkingStrategyName <<Value Object>> {
        -String name
    }

    ParkingBoyConfig o-> ParkingStrategyName
}


package parkinglot <<Aggregate>> {

    class ParkingBoy <<Value Object>> {
        -String name
        -List<ParkingLot> parkingLots
        -ParkingStrategy parkingStrategy
        --
        +Optional<ParkingLot> find()
    }

    class ParkingManager <<Value Object>> {
        -String name
        -List<ParkingBoy> parkingBoys
        --
        +List<ParkingLot> listParkingLotIds()
        +Optional<ParkingLot> findParkingLot()
    }

    class ParkingLot <<Entity>> <<Aggregate Root>> {
        -ParkingLotId id
        -Map<TicketId, Car> ticketToCarMap
        --
        +Ticket park(Car car)
        +Car pick(TicketId ticketId)
    }

    class Ticket <<Value Object>> {
        -String licensePlate
        -ParkingLotId parkingLotId
    }

    class Car <<Value Object>> {
        -String licensePlate
    }

    interface ParkingStrategy {
        Optional<ParkingLot> find(List<ParkingLot> parkingLots)
    }

    class NaturalParkingStrategy <<Value Object>> {
        Optional<ParkingLot> find(List<ParkingLot> parkingLots)
    }

    class MaxSpaceParkingStrategy <<Value Object>> {
        Optional<ParkingLot> find(List<ParkingLot> parkingLots)
    }

    ParkingLot "1" o-- "many" Ticket
    ParkingLot "1" -> "many" Car
    ParkingManager "1" -> "many" ParkingBoy
    ParkingBoy "1" -> "many" ParkingLot
    NaturalParkingStrategy ..|> ParkingStrategy
    MaxSpaceParkingStrategy ..|> ParkingStrategy
    ParkingStrategy --> ParkingBoy
}

@enduml