@startuml parkinglot-sequence
skinparam Shadowing false
skinparam class {
    BackgroundColor PaleTurquoise
    ArrowColor SeaGreen
}

title: "list parking lot"

participant Application
participant ParkingManagerFactory
participant ParkingManagerConfigRepository
participant ParkingManagerConfig
participant ParkingBoyFactory


-> Application: parkingManagerName
activate Application

Application -> ParkingManagerFactory: listsParkingLotWithSpace
activate ParkingManagerFactory

ParkingManagerFactory -> ParkingManagerConfigRepository: findByName
activate ParkingManagerConfigRepository

ParkingManagerConfigRepository --> ParkingManagerFactory: ParkingManagerConfig
activate ParkingManagerFactory

ParkingManagerConfig -> ParkingManagerConfig: getParkingBoyConfigIds
activate ParkingManagerConfig

ParkingManagerConfig -> ParkingBoyFactory: findParkingBoyById
deactivate ParkingManagerConfig

ParkingBoyFactory --> ParkingManagerFactory: List<ParkingBoy>
deactivate ParkingBoyFactory

ParkingManagerFactory --> ParkingManager: parkingManager
deactivate ParkingManagerFactory

ParkingManager --> Application: listParkingLotIds
deactivate ParkingManager


deactivate ParkingManagerFactory
deactivate Application

@enduml