@startuml
skinparam Shadowing false
skinparam sequence {
    ActorBackgroundColor PaleTurquoise
    ArrowColor SeaGreen
    LifeLineBackgroundColor PaleTurquoise
    ParticipantBackgroundColor PaleTurquoise
}

autonumber "[0]"
actor user order 1
participant ParkingApplicationService order 2
participant FindParkingLotService order 3
participant ParkingBoySpecification order 4
participant ParkingLotFinderFactory order 5
participant ParkingLotFinder order 6
participant ParkingLot order 7
participant ParkingLotRepository order 8

user -> ParkingApplicationService :parkWithParkingBoy
ParkingApplicationService -> ParkingBoySpecification :new
ParkingApplicationService <- ParkingBoySpecification :parkingBoySpecification
ParkingApplicationService -> FindParkingLotService :findParkingLot(parkingBoySpecification)
FindParkingLotService -> ParkingBoySpecification :newParkingLotFinder
ParkingBoySpecification -> ParkingLotFinderFactory :newParkingBoy
ParkingBoySpecification <- ParkingLotFinderFactory :parkingLotFinder
FindParkingLotService <- ParkingBoySpecification :parkingLotFinder
FindParkingLotService -> ParkingLotFinder :findParkingLotToPark
FindParkingLotService <- ParkingLotFinder :parkingLot
ParkingApplicationService <- FindParkingLotService :parkingLot
ParkingApplicationService -> ParkingLot :park
ParkingApplicationService <-  ParkingLot :ticket
ParkingApplicationService -> ParkingLotRepository :save(parkingLot)
user <- ParkingApplicationService :ticket

@enduml