@startuml parking context
skinparam Shadowing false
skinparam sequence {
    ActorBackgroundColor PaleTurquoise
    ArrowColor SeaGreen
    LifeLineBackgroundColor PaleTurquoise
    ParticipantBackgroundColor PaleTurquoise
}

title parking by parking boy

autonumber "[0]"
actor user
participant ParkingApplicationService
participant FindParkingLotService
participant ParkingBoySpecification
participant ParkingLotFinder
participant ParkingLot
participant ParkingLotRepository

user -> ParkingApplicationService :parkWithParkingBoy
ParkingApplicationService -> ParkingBoySpecification :new
ParkingApplicationService <- ParkingBoySpecification :parkingBoySpecification
ParkingApplicationService -> FindParkingLotService :findParkingLot(parkingBoySpecification, ParkingLotFinderFactory)
FindParkingLotService -> ParkingBoySpecification :new ParkingLotFinder
ParkingBoySpecification -> FindParkingLotService :ParkingLotFinder
FindParkingLotService -> ParkingLotFinder :findParkingLotToPark
FindParkingLotService <- ParkingLotFinder :parkingLot
ParkingApplicationService <- FindParkingLotService :parkingLot
ParkingApplicationService -> ParkingLot :park
ParkingApplicationService <-  ParkingLot :ticket
ParkingApplicationService -> ParkingLotRepository :save(parkingLot)
user <- ParkingApplicationService :ticket

@enduml